### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by u2** [u2/paper-weekly-bitcoin-ng#1]
问题：

1. 影响比特币交易性能上限的因素有哪些？
2. BitcoinNG 创新点是什么？
3. BitcoinNG 对现在的 Bitcoin 哪些方面有改进？
4. 区块扩容和出块时间变化对 Bitcoin 的影响有哪些？对 BitcoinNG 有哪些影响？
5. BitcoinNG 的区块奖励是如何分配的？为什么要这样设计？
6. 论文中的评估标准主要有哪些？
7. 论文中提到的 GHOST 协议有哪些缺点？

其他问题自行补充。

**Comment by u2** [comment]
笔记：

Despite its potential, blockchain protocols face a significant scalability barrier [51, 36, 19, 5]. The maximum rate at which these systems can process transactions is capped by the choice of two parameters: block size and block interval.Increasing block size improves throughput, but the resulting bigger blocks take longer to propagate in the network. Reducing the block interval reduces latency, but leads to instability where the system is in disagreement and the blockchain is subject to reorganization.

(页码2). 


Bitcoin-NG’s latency is limited only by the propagation delay of the network, and its bandwidth is limited only by the processing capacity of the individual nodes. Bitcoin-NG achieves this performance improvement by decoupling Bitcoin’s blockchain operation into two planes: leader election and transaction serialization.

(页码2). 

In contrast, BitcoinNG improves latency and throughput to the maximum allowed by network conditions and node processing limits, while avoiding the fairness and mining power utilization problems.

(页码3).

**Comment by u2** [comment]
How to resolve short microblock fork ?

Therefore, a user that sees a microblock should wait for the propagation time of the network before considering it in the chain, to make sure it is not pruned by a new key block.

(页码5).

**Comment by u2** [comment]
Microblock Fork Prevention

a poison transaction

(页码5).

**Comment by u2** [comment]
Incentives

(页码6).

**Comment by u2** [comment]
Resilience to Mining Power Variation

(页码7).

**Comment by u2** [comment]
疑问：Consensus delay

(页码10).

**Comment by Virale** [comment]
比特币交易性能主要是带宽和出块延迟的影响（我觉得最主要的是带宽，出块延迟也是根据当时带宽水平设计的。）

而 Bitcoin NG 采用了两类块，一个是类似比特币区块的 key block，在获得 key block 出块权之后这个 miner 可以在 key block 之后下个 key block 被（其他）miner 挖出来之前做 micro block

不理解的是这里在 micro block 之后挖矿，micro block 出块是很快的，下一个产生 key block 的矿工改如何选择正确的 hash （是最新一个的 micro block 的hash）去尝试 nounce？（我理解在 Bitcoin 里面是结合前一个block 的 hash 进行尝试） 

出块奖励部分是 40% 出 key block 的，60% 归下一个 key block。因为下一个 key block 什么时候出来是不确定的，只有一个大致的时间，所以可能在 microblock#5 或者 microblock#6，但是 microblock 是不停在出，所以 keyblock 出来的时候可能会削减掉几个后面的 microblock，这时候奖励分给后面的 key block miner 比较好。

**Comment by u2** [comment]
> 比特币交易性能主要是带宽和出块延迟的影响（我觉得最主要的是带宽，出块延迟也是根据当时带宽水平设计的。）

这里的性能主要指的“吞吐量”和“延迟”。带宽不是比特币协议本身的，这个是所有协议相同的前提。这里主要讲的是块的大小和出块时间延迟，对“吞吐量”和“延迟”的影响。

> 不理解的是这里在 micro block 之后挖矿，micro block 出块是很快的，下一个产生 key block 的矿工改如何选择正确的 hash （是最新一个的 micro block 的hash）去尝试 nounce？（我理解在 Bitcoin 里面是结合前一个block 的 hash 进行尝试）

其实这里矿工是可以选择任何一个micro block，都是符合协议的。为了鼓励下一个key block包含尽量多的micro block，所以有激励分成。这里其实是激励相融的，因为每个key block都会尽量遵守这个规定，这样大家的利益才是最大化的。
